services:
  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    env_file:
      - stack.env

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
